package fyp.nyp.hdbproject.aws;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBDocument;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import org.altbeacon.beacon.Beacon;
import org.altbeacon.beacon.Identifier;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by L30911 on 1/20/2016.
 */
@DynamoDBTable(tableName = "hdb_presence")
public class Presence {
    public String nearestBeaconId;
    public double distance;
    public List<BeaconData> beaconDataList;

    @DynamoDBAttribute(attributeName = "beaconDataList")
    public List<BeaconData> getBeaconData() {
        return beaconDataList;
    }

    public void setBeaconData(List<BeaconData> beaconData) {
        this.beaconDataList = beaconData;
    }

    //Keys
    public long time;
    public String deviceId;

    public void addBeaconData(BeaconData beaconData){
        if(this.beaconDataList == null )
            beaconDataList = new ArrayList<BeaconData>();
        this.beaconDataList.add(beaconData);
    }
    @DynamoDBHashKey(attributeName = "deviceId")
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @DynamoDBAttribute(attributeName="nearestBeaconId")
    public String getNearestBeaconId() {
        return nearestBeaconId;
    }

    public void setNearestBeaconId(String nearestBeaconId) {
        this.nearestBeaconId = nearestBeaconId;
    }
    @DynamoDBAttribute(attributeName="distance")
    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    @DynamoDBAttribute(attributeName = "timestamp")
    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    @DynamoDBDocument
    public static class BeaconData{
        private String beaconID;
        private double distance;

        @DynamoDBAttribute(attributeName = "beaconId")
        public String getBeaconID() {
            return beaconID;
        }

        public void setBeaconID(String beaconID) {
            this.beaconID = beaconID;
        }
        @DynamoDBAttribute(attributeName = "distance")
        public double getDistance() {
            return distance;
        }

        public void setDistance(double distance) {
            this.distance = distance;
        }
    }
}
