// Generated by CoffeeScript 1.10.0
(function() {
  var Beacon,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Beacon = (function() {
    function Beacon(App) {
      this.App = App;
      this.getAllBeacons = bind(this.getAllBeacons, this);
      this.App.router.get("/api/beacons", this.getAllBeacons);
    }

    Beacon.prototype.getAllBeacons = function(req, res) {
      var dynamoDB;
      dynamoDB = new this.App.aws.DynamoDB();
      return dynamoDB.scan({
        TableName: "hdb_beacons"
      }, (function(_this) {
        return function(err, result) {
          return _this.App.sendContent(req, res, _this.App.convertFromArray(result["Items"]));
        };
      })(this));
    };

    return Beacon;

  })();

  module.exports = Beacon;

}).call(this);
